### PR TITLE
updated readme and onboarding_process

### PR DESCRIPTION
**Pull request by tassilomorino**
https://app.zenhub.com/workspaces/senf-60f4774cb34fbf000fed7b7b/issues/agileventures/senf_client/112

### CODE REVIEW

**Review by aonomike — COMMENTED** [review]
Thanks @tassilomorino for great work on this. Would you kindly pull the latest code from main branch to see if the tests still fail?

**Comment by Georgy5** [comment]
Made minor changes, like adding the INSTALLATION INSTRUCTIONS section.

**Review by Georgy5 — APPROVED** [review]
Made minor changes like adding the INSTALLATION INSTRUCTIONS section mentioned in ONBOARDING_PROCESS.md

**Comment by Georgy5** [comment]
> Thanks @tassilomorino for great work on this. Would you kindly pull the latest code from main branch to see if the tests still fail?

@aonomike Do you think that it affects the Github Actions workflow test?

**Comment by ArcAnya** [comment]
LGTM

**Pull request merged**
