### PR TITLE
Add .nvmrc

### LINKED ISSUE #56: Add .nvmrc to project

### PR DESCRIPTION
**Pull request by Georgy5**
Fixes #56

#### Description
Added .nvmrc file with Node version 14.17.4

#### Motivation and Context
Ensure that all project contributors are using the same node version to avert possible issus which may arise if everyone is developing on different versions.

#### Requirements
[Node Version Manager](https://github.com/nvm-sh/nvm)

#### Notes
The file could also just say 16.6 for the node version, to make nvm default to the latest 16.6 release.
See the official documentation on [.nvmrc](https://github.com/nvm-sh/nvm#nvmrc)

Apparently creating the .nvmrc is not enough for the the specified node version to be loaded automatically.
One needs to run `nvm use` inside the project folder!

 If specified node version is not installed simply run `nvm install`

### CODE REVIEW

**Comment by Georgy5** [comment]
One can setup ones Terminal Shell to run `nvm use` automatically every time there's a .nvmrc file in the directory
Relevant StackOverflow post [link](https://stackoverflow.com/questions/23556330/run-nvm-use-automatically-every-time-theres-a-nvmrc-file-on-the-directory)
Shorter gist for OhMyZsh shell if nmv is installed[ link](https://gist.github.com/alwayrun/38ca5bb35a22451dec469f04671d30a5)

**Comment by Georgy5** [comment]
### TODO
The question is which node version to lock the project into??

**Comment by Georgy5** [comment]
So Tassilo informed me that the project was started using Node version 8. In today's meeting we all agreed on using the latest Node version (v16), because why not?!

**Comment by Georgy5** [comment]
I just noticed that this PR  accidentally includes a git commit where I deleted the example environment variable file `.env.example`
It's not ideal, but it also shouldn't be a problem as it is literally just an example and should be deleted eventually anyway.

**Review by aonomike — APPROVED** [review]
LGTM

**Review by cde — APPROVED** [review]
Looks good to me!

**Pull request merged**
